---
title: "Multivariate meta analysis"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    number_sections: no
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)
```

```{r}

# disable scientific notation
options(scipen = 999) 

# dependencies
library(tidyverse)
library(metafor)

# devtools::install_github(ianhussey/timesavers)
library(timesavers)

```

# Multivariate meta analysis

```{r}

# get data
data <- read.csv("multivariate meta analysis data.csv")

# fit
fit <- rma.mv(yi     = yi, 
              V      = V,   # variance is denoted differently to the rma() funciton, which uses vi
              random = ~ 1 | Experiment,   # assuming no moderators are being tested, specify an intercept only model that clusters the DVs by their source. In this case Experiment, but could be Article etc depending on your data.
              data   = data,
              slab   = paste(Experiment, outcome))

# plot
forest(fit,
       xlab = "Cohen's d",
       addcred = TRUE,
       refline = 0)

# model results and heterogeneity stats
p_value <- timesavers::apa_p_value(fit$pval)  

meta_analysis_results <-
  predict(fit, digits = 5) %>%
  as.data.frame() %>%
  gather() %>%
  round_df(2) %>%
  dplyr::rename(metric = key,
                estimate = value) %>%
  mutate(metric = dplyr::recode(metric,
                                "pred"  = "Meta analysed Cohen's d",
                                "ci.lb" = "95% CI lower",
                                "ci.ub" = "95% CI upper",
                                "cr.lb" = "95% CR lower",
                                "cr.ub" = "95% CR upper"))

meta_analysis_results <- rbind(meta_analysis_results,
                               data.frame(metric = "p",
                                          estimate = p_value))

# summarize results
meta_analysis_results_text <- 
  paste0("k = ", fit$k, ", ", 
         "Cohen's d = ", meta_analysis_results$estimate[1],
         # dynamic indexing of some values as different models return variables in different locations, but relative location is reliable
         ", 95% CI = [", meta_analysis_results$estimate[length(meta_analysis_results$estimate)-4],  
         ", ", meta_analysis_results$estimate[length(meta_analysis_results$estimate)-3], 
         "], 95% CR = [", meta_analysis_results$estimate[length(meta_analysis_results$estimate)-2], 
         ", ", meta_analysis_results$estimate[length(meta_analysis_results$estimate)-1],
         "], p ", meta_analysis_results$estimate[length(meta_analysis_results$estimate)])

heterogeneity_test_results_text <- 
  paste0("Q(df = ",    fit$k - 1, ") = ", round(fit$QE, 2), 
         ", p ",       fit$QEp,
         ", tau^2 = ", round(fit$tau2, 2))

```

Meta analysed effect size: `r meta_analysis_results_text`

Hetergeneity tests: `r heterogeneity_test_results_text`

NB I^2 and H^2 metrics also possible for multi-level models but you have to extract them manually, see http://www.metafor-project.org/doku.php/tips:i2_multilevel_multivariate 




