---
title: "Multivariate meta analysis"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    number_sections: no
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)
```

```{r}

# disable scientific notation
options(scipen = 999) 

# dependencies
library(tidyverse)
library(metafor)

# devtools::install_github(ianhussey/timesavers)
library(timesavers)

```

# Get data

```{r}

# get data
results_for_meta_analysis_h1 <- read.csv("../../meta analysis data/results_for_meta_analysis_iat.csv")
results_for_meta_analysis_h2 <- read.csv("../../meta analysis data/results_for_meta_analysis_self_report.csv")
results_for_meta_analysis_h3 <- read.csv("../../meta analysis data/results_for_meta_analysis_behavioural_intentions.csv")

# combine
data <- bind_rows(mutate(results_for_meta_analysis_h1,
                         outcome = "IAT"),
                  mutate(results_for_meta_analysis_h2,
                         outcome = "self-report"),
                  mutate(results_for_meta_analysis_h3,
                         outcome = "behavioural intentions",
                         # convert ORs into cohen's d values
                         ci_lwr = OR_to_d(exp(yi - sei*1.96)),
                         ci_upr = OR_to_d(exp(yi + sei*1.96)),
                         yi = OR_to_d(exp(yi)),
                         sei = (ci_upr - ci_lwr)/(1.96*2))) %>%
  mutate(V = sei^2) %>%
  select(Experiment, outcome, yi, V) %>%
  filter(Experiment != "Experiment 2")

```

# Multivariate meta analysis

random slope for outcome and intercept for study.

```{r}

# fit
fit <- rma.mv(yi     = yi, 
              V      = V,   # variance is denoted differently to the rma() funciton, which uses vi
              random = ~ outcome | Experiment,   # assuming no moderators are being tested, specify a random slope and intercept model that clusters the DVs by their source and the slopes by the DV.
              data   = data,
              slab   = paste(Experiment, outcome))

fit

# plot
forest(fit,
       xlab = "Cohen's d",
       addcred = TRUE,
       refline = 0)

# model results and heterogeneity stats
meta_analysis_results <-
  predict(fit, digits = 5) %>%
  as.data.frame() %>%
  gather() %>%
  round_df(2) %>%
  dplyr::rename(metric = key,
                estimate = value) %>%
  mutate(metric = dplyr::recode(metric,
                                "pred"  = "Meta analysed Cohen's d",
                                "ci.lb" = "95% CI lower",
                                "ci.ub" = "95% CI upper",
                                "cr.lb" = "95% CR lower",
                                "cr.ub" = "95% CR upper"))

meta_analysis_results <- rbind(meta_analysis_results,
                               data.frame(metric = "p",
                                          estimate = fit$pval))

# summarize results
meta_analysis_results_text <- 
  paste0("k = ", fit$k, ", ", 
         "Cohen's d = ", meta_analysis_results$estimate[1],
         # dynamic indexing of some values as different models return variables in different locations, but relative location is reliable
         ", 95% CI = [", meta_analysis_results$estimate[3],  
         ", ", meta_analysis_results$estimate[4], 
         "], 95% CR = [", meta_analysis_results$estimate[5], 
         ", ", meta_analysis_results$estimate[6],
         "], p = ", meta_analysis_results$estimate[length(meta_analysis_results$estimate)])

heterogeneity_test_results_text <- 
  paste0("Q(df = ",    fit$k - 1, ") = ", round(fit$QE, 2), 
         ", p ",       fit$QEp,
         ", tau^2 = ", round(fit$tau2, 2))

```

Meta analysed effect size: `r meta_analysis_results_text`

Hetergeneity tests: `r heterogeneity_test_results_text`

