---
title: "Data processing"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    number_sections: no
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)
```

```{r}

# disable scientific notation
options(scipen = 999) 

# dependencies
library(tidyverse)
library(foreign)

```

# Data processing

```{r}

# convert SPSS to csv
input_data_exp_1 <- 
  read.spss("../experiment 1/data/processed/Shared_Features_Study_1_FINAL.sav", to.data.frame = TRUE)

input_data_exp_2 <- 
  read.spss("../experiment 2/data/processed/Shared_Features_Study_2_FINAL.sav", to.data.frame = TRUE)

input_data_exp_3 <- 
  read.spss("../experiment 3/data/processed/Shared_Features_Study_3_FINAL.sav", to.data.frame = TRUE)

input_data_exp_4 <- 
  read.spss("../experiment 4/data/processed/Shared_Features_Study_4_FINAL.sav", to.data.frame = TRUE)

input_data_exp_5 <- 
  read.spss("../experiment 5/data/processed/Shared_Features_Study_5_FINAL.sav", to.data.frame = TRUE)

input_data_exp_6 <- 
  read.spss("../experiment 6/data/processed/Shared_Features_Study_6_FINAL.sav", to.data.frame = TRUE)

input_data_exp_7 <- 
  read.spss("../experiment 7/data/processed/Shared_Features_Study_7_FINAL.sav", to.data.frame = TRUE)

input_data_exp_8 <- 
  read.spss("../experiment 8/data/processed/Shared_Features_Study_8_FINAL.sav", to.data.frame = TRUE)

input_data_exp_9 <- 
  read.spss("../experiment 9/data/processed/Shared_Features_Study_9_FINAL.sav", to.data.frame = TRUE)


write_csv(input_data_exp_1, "../experiment 1/data/processed/data_processed.csv")
write_csv(input_data_exp_2, "../experiment 2/data/processed/data_processed.csv")
write_csv(input_data_exp_3, "../experiment 3/data/processed/data_processed.csv")
write_csv(input_data_exp_4, "../experiment 4/data/processed/data_processed.csv")
write_csv(input_data_exp_5, "../experiment 5/data/processed/data_processed.csv")
write_csv(input_data_exp_6, "../experiment 6/data/processed/data_processed.csv")
write_csv(input_data_exp_7, "../experiment 7/data/processed/data_processed.csv")
write_csv(input_data_exp_8, "../experiment 8/data/processed/data_processed.csv")
write_csv(input_data_exp_9, "../experiment 9/data/processed/data_processed.csv")

# tidy data
data_exp_1 <- read.csv("../experiment 1/data/processed/data_processed.csv") %>%
  mutate(intention = str_remove_all(Intentions_response, " "),
         intention = str_remove_all(intention, "Iwouldtry"),
         intention = as.factor(intention),
         color_valence_contingency_memory = ifelse(Total_CS_Color_Contingency_Score == 2, TRUE, FALSE),
         US_contingency_memory = ifelse(Total_US_Contingency_Score == 2, TRUE, FALSE),
         hypothesis_awareness = ifelse(Hypothesis_Awareness_recoded == 1, TRUE, FALSE),
         influence_awareness = ifelse(Influence_Awareness_recoded == 1, TRUE, FALSE),
         reactance_IAT = ifelse(Reactance_IAT == 1, TRUE, FALSE), 
         reactance_self_reports = ifelse(Reactance_Self_Reports == 1, TRUE, FALSE),
         demand_IAT = ifelse(Demand_IAT == 1, TRUE, FALSE), 
         demand_self_reports = ifelse(Demand_Self_Reports == 1, TRUE, FALSE)) %>%
  mutate(source_valence_condition = as.factor(str_replace_all(as.character(Color_Matching), " ", ""))) %>%
  select(Participant, 
         Age, 
         Gender,
         source_valence_condition,
         IAT_Score,
         EC_Effect_CS1_CS2_Difference_Score,
         intention,
         color_valence_contingency_memory,
         US_contingency_memory,
         hypothesis_awareness,
         influence_awareness,
         reactance_IAT,
         reactance_self_reports,
         demand_IAT,
         demand_self_reports) %>%
  # exclude participants with partial data
  na.omit()

data_exp_2 <- read.csv("../experiment 2/data/processed/data_processed.csv") %>%
  mutate(intention = str_remove_all(Intentions_response, " "),
         intention = str_remove_all(intention, "Iwouldtry"),
         intention = as.factor(intention),
         color_valence_contingency_memory = ifelse(Total_CS_Color_Contingency_Score == 2, TRUE, FALSE),
         US_contingency_memory = ifelse(Total_US_Contingency_Score == 2, TRUE, FALSE),
         hypothesis_awareness = ifelse(Hypothesis_Awareness_recoded == 1, TRUE, FALSE),
         influence_awareness = ifelse(Influence_Awareness_recoded == 1, TRUE, FALSE),
         reactance_IAT = ifelse(Reactance_IAT == 1, TRUE, FALSE), 
         reactance_self_reports = ifelse(Reactance_Self_Reports == 1, TRUE, FALSE),
         demand_IAT = ifelse(Demand_IAT == 1, TRUE, FALSE), 
         demand_self_reports = ifelse(Demand_Self_Reports == 1, TRUE, FALSE)) %>%
  mutate(source_valence_condition = as.factor(str_replace_all(as.character(Color_Matching), " ", ""))) %>%
  select(Participant,
         Age, 
         Gender,
         source_valence_condition,
         IAT_Score,
         EC_Effect_CS1_CS2_Difference_Score,
         intention,
         color_valence_contingency_memory,
         US_contingency_memory,
         hypothesis_awareness,
         influence_awareness,
         reactance_IAT,
         reactance_self_reports,
         demand_IAT,
         demand_self_reports) %>%
  # exclude participants with partial data
  na.omit()

data_exp_3 <- read.csv("../experiment 3/data/processed/data_processed.csv") %>%
  mutate(intention = str_remove_all(Intentions_response, " "),
         intention = str_remove_all(intention, "Iwouldtry"),
         intention = as.factor(intention),
         color_valence_contingency_memory = ifelse(Total_CS_Color_Contingency_Score == 2, TRUE, FALSE),
         US_contingency_memory = ifelse(Total_US_Contingency_Score == 2, TRUE, FALSE),
         hypothesis_awareness = ifelse(Hypothesis_Awareness_recoded == 1, TRUE, FALSE),
         influence_awareness = ifelse(Influence_Awareness_recoded == 1, TRUE, FALSE),
         reactance_IAT = ifelse(Reactance_IAT == 1, TRUE, FALSE), 
         reactance_self_reports = ifelse(Reactance_Self_Reports == 1, TRUE, FALSE),
         demand_IAT = ifelse(Demand_IAT == 1, TRUE, FALSE), 
         demand_self_reports = ifelse(Demand_Self_Reports == 1, TRUE, FALSE)) %>%
  mutate(source_valence_condition = as.factor(str_replace_all(as.character(Color_Matching), " ", ""))) %>%
  select(Participant, 
         Age, 
         Gender,
         source_valence_condition,
         IAT_Score,
         EC_Effect_CS1_CS2_Difference_Score,
         intention,
         color_valence_contingency_memory,
         US_contingency_memory,
         hypothesis_awareness,
         influence_awareness,
         reactance_IAT,
         reactance_self_reports,
         demand_IAT,
         demand_self_reports) %>%
  # exclude participants with partial data
  na.omit()

data_exp_4 <- read.csv("../experiment 4/data/processed/data_processed.csv") %>%
  mutate(intention = str_remove_all(Intentions_response, " "),
         intention = str_remove_all(intention, "Iwouldtry"),
         intention = as.factor(intention),
         color_valence_contingency_memory = ifelse(Total_CS_Size_Contingency_Score == 2, TRUE, FALSE),
         US_contingency_memory = ifelse(Total_US_Contingency_Score == 2, TRUE, FALSE),
         hypothesis_awareness = ifelse(Hypothesis_Awareness_recoded == 1, TRUE, FALSE),
         influence_awareness = ifelse(Influence_Awareness_recoded == 1, TRUE, FALSE),
         reactance_IAT = ifelse(Reactance_IAT == 1, TRUE, FALSE), 
         reactance_self_reports = ifelse(Reactance_Self_Reports == 1, TRUE, FALSE),
         demand_IAT = ifelse(Demand_IAT == 1, TRUE, FALSE), 
         demand_self_reports = ifelse(Demand_Self_Reports == 1, TRUE, FALSE)) %>%
  mutate(source_valence_condition = as.factor(str_replace_all(as.character(Size_Matching), " ", ""))) %>%
  select(Participant, 
         Age, 
         Gender,
         source_valence_condition,
         IAT_Score,
         EC_Effect_CS1_CS2_Difference_Score,
         intention,
         color_valence_contingency_memory,
         US_contingency_memory,
         hypothesis_awareness,
         influence_awareness,
         reactance_IAT,
         reactance_self_reports,
         demand_IAT,
         demand_self_reports) %>%
  # exclude participants with partial data
  na.omit()

data_exp_5 <- read.csv("../experiment 5/data/processed/data_processed.csv") %>%
  mutate(intention = str_remove_all(Intentions_response, " "),
         intention = str_remove_all(intention, "Iwouldtry"),
         intention = as.factor(intention),
         color_valence_contingency_memory = ifelse(Total_CS_Color_Contingency_Score == 4, TRUE, FALSE),
         US_contingency_memory = ifelse(Total_US_Contingency_Score == 2, TRUE, FALSE),
         hypothesis_awareness = ifelse(Hypothesis_Awareness_recoded == 1, TRUE, FALSE),
         influence_awareness = ifelse(Influence_Awareness_recoded == 1, TRUE, FALSE),
         color_training = ifelse(Total_Color_Training_Score == 4, TRUE, FALSE), 
         reactance_IAT = ifelse(Reactance_IAT == 1, TRUE, FALSE), 
         reactance_self_reports = ifelse(Reactance_Self_Reports == 1, TRUE, FALSE),
         demand_IAT = ifelse(Demand_IAT == 1, TRUE, FALSE), 
         demand_self_reports = ifelse(Demand_Self_Reports == 1, TRUE, FALSE)) %>%
  mutate(source_valence_condition = as.factor(str_replace_all(as.character(Color_Matching), " ", ""))) %>%
  select(Participant, 
         Age, 
         Gender,
         source_valence_condition,
         IAT_Score,
         EC_Effect_CS1_CS2_Difference_Score,
         intention,
         color_valence_contingency_memory,
         US_contingency_memory,
         hypothesis_awareness,
         influence_awareness,
         color_training,
         reactance_IAT,
         reactance_self_reports,
         demand_IAT,
         demand_self_reports) %>%
  # exclude participants with partial data
  na.omit()

data_exp_6 <- read.csv("../experiment 6/data/processed/data_processed.csv") %>%
  mutate(intention = str_remove_all(Intentions_response, " "),
         intention = str_remove_all(intention, "Iwouldtry"),
         intention = as.factor(intention),
         us_valence_contingency_memory = ifelse(Total_US_Valence_Contingency_Score == 2, TRUE, FALSE),
         CS_contingency_memory = ifelse(Total_CS_US_Contingency_Score == 2, TRUE, FALSE),
         hypothesis_awareness = ifelse(Hypothesis_Awareness_recoded == 1, TRUE, FALSE),
         influence_awareness = ifelse(Influence_Awareness_recoded == 1, TRUE, FALSE),
         reactance_IAT = ifelse(Reactance_IAT == 1, TRUE, FALSE), 
         reactance_self_reports = ifelse(Reactance_Self_Reports == 1, TRUE, FALSE),
         demand_IAT = ifelse(Demand_IAT_recoded == 1, TRUE, FALSE), 
         demand_self_reports = ifelse(Demand_Self_Reports_recoded == 1, TRUE, FALSE)) %>%
  mutate(source_valence_condition = as.factor(str_replace_all(as.character(Color_Matching), " ", ""))) %>%
  select(Participant, 
         Age, 
         Gender,
         source_valence_condition,
         IAT_Score,
         EC_Effect_CS1_CS2_Difference_Score,
         intention,
         us_valence_contingency_memory,
         CS_contingency_memory,
         hypothesis_awareness,
         influence_awareness,
         reactance_IAT,
         reactance_self_reports,
         demand_IAT,
         demand_self_reports) %>%
  # exclude participants with partial data
  na.omit()

data_exp_7 <- read.csv("../experiment 7/data/processed/data_processed.csv") %>%
  mutate(intention = str_remove_all(Intentions_response, " "),
         intention = str_remove_all(intention, "Iwouldtry"),
         intention = as.factor(intention),
         color_valence_contingency_memory = ifelse(Total_CS_Size_Contingency_Score == 2, TRUE, FALSE),
         US_contingency_memory = ifelse(Total_US_Contingency_Score == 2, TRUE, FALSE),
         hypothesis_awareness = ifelse(Hypothesis_Awareness_recoded == 1, TRUE, FALSE),
         influence_awareness = ifelse(Influence_Awareness_recoded == 1, TRUE, FALSE),
         reactance_IAT = ifelse(Reactance_IAT == 1, TRUE, FALSE), 
         reactance_self_reports = ifelse(Reactance_Self_Reports == 1, TRUE, FALSE),
         demand_IAT = ifelse(Demand_IAT == 1, TRUE, FALSE), 
         demand_self_reports = ifelse(Demand_Self_Reports == 1, TRUE, FALSE)) %>%
  mutate(source_valence_condition = as.factor(str_replace_all(as.character(Size_Matching), " ", ""))) %>%
  select(Participant, 
         Age, 
         Gender,
         source_valence_condition,
         EP_Score,
         EC_Effect_CS1_CS2_Difference_Score,
         intention,
         color_valence_contingency_memory,
         US_contingency_memory,
         hypothesis_awareness,
         influence_awareness,
         reactance_IAT,
         reactance_self_reports,
         demand_IAT,
         demand_self_reports) %>%
  # exclude participants with partial data
  na.omit()

data_exp_8 <- read.csv("../experiment 8/data/processed/data_processed.csv") %>%
  mutate(US_contingency_memory = ifelse(US_Contingency_Awareness_recoded == 1, TRUE, FALSE),
         hypothesis_awareness = ifelse(Hypothesis_Awareness_recoded == 1, TRUE, FALSE),
         influence_awareness = ifelse(Influence_Awareness_recoded == 1, TRUE, FALSE),
         reactance_IAT = ifelse(Reactance_IAT == 1, TRUE, FALSE), 
         reactance_self_reports = ifelse(Reactance_Self_Reports == 1, TRUE, FALSE),
         demand_IAT = ifelse(Demand_IAT == 1, TRUE, FALSE), 
         demand_self_reports = ifelse(Demand_Self_Reports == 1, TRUE, FALSE),
         source_valence_condition = ifelse(str_detect(as.character(Stimulus_Identity), "Chris_Good_James_Bad"), "CS2_Positive_CS1_Negative",
                                           ifelse(str_detect(as.character(Stimulus_Identity), "Chris_Bad_James_Good"), "CS1_Positive_CS2_Negative", as.character(Stimulus_Identity)))) %>%
  mutate(Bag_Matching = as.factor(str_replace_all(as.character(Bag_Matching), " ", ""))) %>%
  select(Participant, 
         Age, 
         Gender,
         source_valence_condition,
         Bag_Matching,
         IAT_Score,
         EC_Effect_CS1_CS2_Difference_Score,
         US_contingency_memory,
         hypothesis_awareness,
         influence_awareness,
         reactance_IAT,
         reactance_self_reports,
         demand_IAT,
         demand_self_reports) %>%
  # exclude participants with partial data
  drop_na(-influence_awareness)

data_exp_9 <- read.csv("../experiment 9/data/processed/data_processed.csv") %>%
  mutate(US_contingency_memory = ifelse(US_Contingency_Awareness_recoded == 1, TRUE, FALSE),
         influence_awareness = ifelse(Influence_Awareness_recoded == 1, TRUE, FALSE),
         reactance_IAT = ifelse(Reactance_IAT == 1, TRUE, FALSE), 
         reactance_self_reports = ifelse(Reactance_Self_Reports == 1, TRUE, FALSE),
         demand_IAT = ifelse(Demand_IAT == 1, TRUE, FALSE), 
         demand_self_reports = ifelse(Demand_Self_Reports == 1, TRUE, FALSE),
         source_valence_condition = Stimulus_Identity) %>%
  mutate(Bag_Matching = as.factor(str_replace_all(as.character(Bag_Matching), " ", ""))) %>%
  select(Participant, 
         Age, 
         Gender,
         source_valence_condition,
         Bag_Matching,
         IAT_Score,
         EC_Effect_CS1_CS2_Difference_Score,
         US_contingency_memory,
         influence_awareness,
         reactance_IAT,
         reactance_self_reports,
         demand_IAT,
         demand_self_reports) %>%
  # exclude participants with partial data
  drop_na(-influence_awareness)

# write to disk
write_csv(data_exp_1, "../experiment 1/data/processed/data_for_analysis.csv")
write_csv(data_exp_2, "../experiment 2/data/processed/data_for_analysis.csv")
write_csv(data_exp_3, "../experiment 3/data/processed/data_for_analysis.csv")
write_csv(data_exp_4, "../experiment 4/data/processed/data_for_analysis.csv")
write_csv(data_exp_5, "../experiment 5/data/processed/data_for_analysis.csv")
write_csv(data_exp_6, "../experiment 6/data/processed/data_for_analysis.csv")
write_csv(data_exp_7, "../experiment 7/data/processed/data_for_analysis.csv")
write_csv(data_exp_8, "../experiment 8/data/processed/data_for_analysis.csv")
write_csv(data_exp_9, "../experiment 9/data/processed/data_for_analysis.csv")

```

